# Generated by Django 5.0.3 on 2024-03-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_task_donde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='donde',
            new_name='done',
        ),
    ]
